name: Build & Release

on:
  push:
    branches: ["main"]
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org/"
      - run: |
          npm ci
          npm run build
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          npm version patch -m "chore(release): %s"
          git checkout main
          git push origin main --tags
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}
          npm config set scope "@vclmbv"
          npm adduser --scope=@vclmbv --registry=https://registry.npmjs.org
          npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
