name: Build & Release

on: 
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  release: 
    name: release
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org/"
      - run: npm ci
      - run: npm run build
      - run: npm run version
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
